name: Docker Build Demo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

    
      - name: Build Docker Image
        run: docker build -t demo-image ./examples

